### ISSUE TITLE
Reconnect automatically to server

### ISSUE THREAD

**Issue by TheGreatestJannet** [hivecom/pokebot#58]
**Is your feature request related to a problem? Please describe.**
Currently if the server goes down the bot needs to be manually restarted to reconnect to the server.

**Describe the solution you'd like**
The bot should automatically reconnect the server when it the server comes back online without any manual intervention.

**Comment by Jokler** [comment]
I run the bot as a [systemd service](https://github.com/Mavulp/pokebot/blob/master/systemd/pokebot.service) so it restarts automatically if it shuts down (which it should if it disconnects).
I can look into making it reconnect in the next few days though since that should be part of the bot in my opinion.

**Comment by TheGreatestJannet** [comment]
While a systemd service that restarts if teamspeak service restarts it is a great idea, unfortunately that only works if you are running both on the same server which I am not.

**Comment by Jokler** [comment]
The service does not restart when the server restarts, it restarts if the bot stops running.
That is what this line says:
https://github.com/Mavulp/pokebot/commit/9234b78b507dfd774f8a876c9740814e68427057#diff-c0b5380f10e5cf4e4db960934a25040aR11

**Comment by TheGreatestJannet** [comment]
Oh sorry! I have just checked my systemd file and I have the exact same file as you however it doesn’t restart the bot if it loses connection the server as it seems the bot keeps running anyway.
